BlockSettle/common

BlocksettleNetworkingLib/HeadlessContainerListener.cpp
BlocksettleNetworkingLib/HeadlessContainerListener.h
BlocksettleNetworkingLib/TradesUtils.cpp
BlocksettleNetworkingLib/Wallets/SyncHDGroup.cpp
BlocksettleNetworkingLib/Wallets/SyncWalletsManager.cpp

Based on #1871, so need to merge it first

BST-2598: fix settlement outputs

---

BlocksettleNetworkingLib/HeadlessContainer.cpp
BlocksettleNetworkingLib/HeadlessContainer.h
BlocksettleNetworkingLib/HeadlessContainerListener.cpp
BlocksettleNetworkingLib/HeadlessContainerListener.h
BlocksettleNetworkingLib/SignContainer.h
Blocksettle_proto/Communication/bs_signer.proto
Blocksettle_proto/Communication/headless.proto
WalletsLib/CheckRecipSigner.cpp

http://185.213.153.35:8081/browse/BST-2614

Add signer visibility messages

---

Blocksettle_proto/Communication/bs_server_storage.proto
Blocksettle_proto/Communication/pb_cli.proto

Part of https://github.com/scomil/BS_Private/pull/1098

Constants to db

---

BlocksettleNetworkingLib/Wallets/SyncHDLeaf.cpp
BlocksettleNetworkingLib/Wallets/SyncHDLeaf.h

Allow detect native/nested/non-sw leaf types

Add method to get sync wallet type

---

BlocksettleNetworkingLib/Wallets/SyncWalletsManager.cpp
BlocksettleNetworkingLib/Wallets/SyncWalletsManager.h

Issue: change unordered_map to multimap in return devices type, as far as device key always the same for ledger devices

Add ledger support

---

BlocksettleNetworkingLib/ApplicationSettings.cpp

http://185.213.153.35:8081/browse/BST-2637

Change link address for login

---

BlocksettleNetworkingLib/SelectedTransactionInputs.cpp
BlocksettleNetworkingLib/SelectedTransactionInputs.h
BlocksettleNetworkingLib/TransactionData.cpp
BlocksettleNetworkingLib/TransactionData.h
BlocksettleNetworkingLib/Wallets/SyncHDGroup.cpp
BlocksettleNetworkingLib/Wallets/SyncHDGroup.h

Issue:
1. Add function to get leaf by purpose
2. Disallow to create SelectedTransactionInputs with group, to make possible to filter out leafs from it

Allow finding leaf by purpose and change tx input interface

---

BlocksettleNetworkingLib/HeadlessContainer.cpp
BlocksettleNetworkingLib/HeadlessContainerListener.cpp
WalletsLib/CoreWallet.cpp
WalletsLib/CoreWallet.h

Issue: add support to signer to allow mixing native and nested segwit for ledger tx

Fix mixing segwit support for ledger

---

BlocksettleNetworkingLib/HeadlessContainerListener.cpp

Issue: avoid to use assert in release build explicitly for operation

Avoid to use assert instruction

---

BlocksettleNetworkingLib/ApplicationSettings.cpp

Issue: http://185.213.153.35:8081/browse/BST-2657

Make advanced create tx dialog by default

---

BlocksettleNetworkingLib/ChatProtocol/ChatClientLogic.cpp
BlocksettleNetworkingLib/ChatProtocol/ChatClientLogic.h
BlocksettleNetworkingLib/ChatProtocol/ChatClientService.cpp
BlocksettleNetworkingLib/ChatProtocol/ChatClientService.h
BlocksettleNetworkingLib/ChatProtocol/ClientDBLogic.cpp
BlocksettleNetworkingLib/ChatProtocol/ClientDBLogic.h
BlocksettleNetworkingLib/ChatProtocol/ClientDBService.cpp
BlocksettleNetworkingLib/ChatProtocol/ClientDBService.h

Please merge with chat_fixes branch in bs_dev repo.
Tested on Windows.

Chat - view all history messages - logic part

---

BlocksettleNetworkingLib/OtcTypes.h

Issue: we need to have wallet purpose when create payout for hw wallet

Add wallet purpose to otc offer

---

BlocksettleNetworkingLib/AddressVerificator.cpp
BlocksettleNetworkingLib/ApplicationSettings.cpp
BlocksettleNetworkingLib/ApplicationSettings.h
BlocksettleNetworkingLib/ArmoryServersProvider.cpp
BlocksettleNetworkingLib/PasswordDialogData.cpp
BlocksettleNetworkingLib/PasswordDialogData.h

Issues:
1. Change Armory -> BlockSettle
2. Add flag to password dialog data to expand tx info based on terminal request

Ui related changes

---

BlocksettleNetworkingLib/ApplicationSettings.cpp
BlocksettleNetworkingLib/ApplicationSettings.h

Delete unneeded flag HideCreateAccountPromptTestnet

---

BlocksettleNetworkingLib/ColoredCoinLogic.cpp
BlocksettleNetworkingLib/ColoredCoinLogic.h

cc candidate method, stricter checks for ColoredCoinTrackerClient::isTxHashValid, fixes for ColoredCoinTracker::processTx

Cc candidate

---

BlocksettleNetworkingLib/QWalletInfo.cpp
BlocksettleNetworkingLib/QWalletInfo.h
BlocksettleNetworkingLib/TransactionData.cpp
BlocksettleNetworkingLib/TransactionData.h

Issues:
1. Add support function to detect wo wallet info
2. Add functions to correctly update programmatically checking utxo in TransactionData

Ui improvements

---

Blocksettle_proto/Communication/bs_server.proto
Blocksettle_proto/Communication/bs_server_storage.proto

CC handshake fixes

---

BlocksettleNetworkingLib/BSErrorCode.h
BlocksettleNetworkingLib/BSErrorCodeStrings.h
BlocksettleNetworkingLib/OfflineSigner.cpp
BlocksettleNetworkingLib/OfflineSigner.h
BlocksettleNetworkingLib/ProtobufHeadlessUtils.cpp
BlocksettleNetworkingLib/TradesUtils.cpp
BlocksettleNetworkingLib/TransactionData.cpp
BlocksettleNetworkingLib/Wallets/SyncWallet.cpp
BlocksettleNetworkingLib/Wallets/SyncWallet.h
Blocksettle_proto/Communication/headless.proto
Blocksettle_proto/Storage/signer.proto
WalletsLib/CoreWallet.h

http://185.213.153.35:8081/browse/BST-2712

Do not allow broadcast offline OTC from terminal

---

BlocksettleNetworkingLib/Wallets/SyncWallet.cpp
BlocksettleNetworkingLib/Wallets/SyncWallet.h

The lock is only required for unit test

Fix for unit tests

---

BlocksettleNetworkingLib/QSeed.cpp
BlocksettleNetworkingLib/QSeed.h
CommonLib/Bip39.cpp
CommonLib/Bip39.h
WalletsLib/CoreWallet.cpp
WalletsLib/CoreWallet.h
build_scripts/bip_protocols_settings.py

Add bip39 support

---

build_scripts/bip_protocols_settings.py

Issue: fix bip build script revision number instead of fetching only latest master

Fix bip build script revision

---

CommonLib/AUTHORS
CommonLib/Bip39.cpp
CommonLib/Bip39.h

Issue: provide correct license info for a bip39 files

Update bip39 license info

---

BlocksettleNetworkingLib/CommonTypes.h
BlocksettleNetworkingLib/HeadlessContainer.cpp
BlocksettleNetworkingLib/HeadlessContainer.h
BlocksettleNetworkingLib/HeadlessContainerListener.cpp
BlocksettleNetworkingLib/InprocSigner.cpp
BlocksettleNetworkingLib/InprocSigner.h
BlocksettleNetworkingLib/OfflineSigner.cpp
BlocksettleNetworkingLib/ProtobufHeadlessUtils.cpp
BlocksettleNetworkingLib/SignContainer.h
BlocksettleNetworkingLib/Wallets/SyncWallet.cpp
BlocksettleNetworkingLib/Wallets/SyncWallet.h
BlocksettleNetworkingLib/Wallets/SyncWalletsManager.cpp
BlocksettleNetworkingLib/Wallets/SyncWalletsManager.h
WalletsLib/CheckRecipSigner.h
WalletsLib/CoreWallet.cpp
WalletsLib/CoreWallet.h
WalletsLib/TradesVerification.cpp
WalletsLib/TradesVerification.h

All tests seem to pass, manual transactions are successfully broadcasted.
Please report any issues with TX parsing/signing/serialization.

Signer serialization changes

---

CommonLib/Bip39.cpp

Fix build error on linux

---

Blocksettle_proto/Communication/bs_server.proto
Blocksettle_proto/Communication/bs_server_matching.proto

Should be merged with corresponding PR to PB

Remove unused message

---

BlocksettleNetworkingLib/XBTTradeData.h
Blocksettle_proto/Communication/bs_server.proto

Merge with corresponding PR to PB

Update XBT trade info

---

WalletsLib/TradesVerification.cpp

add sanity checks around Tx object deserialization for payin/payout sig checks

add sanity checks

---

BlocksettleNetworkingLib/TradesUtils.cpp
build_scripts/trezor_common_settings.py

Send supportingTXs for all inputs for XBT trades (new Trezor's requirement)

Fix for latest Trezor firmware

---

BlocksettleNetworkingLib/Wallets/SyncHDLeaf.cpp
WalletsLib/ArmoryConnection.cpp
WalletsLib/TradesVerification.cpp

Armory reconnect fixes

---

WalletsLib/WalletUtils.cpp
WalletsLib/WalletUtils.h

Let's not overoptimize things before it's really needed. Keeping code simple can save a lot of time at debugging unexplained behavior.

Changed function proto

---

BlocksettleNetworkingLib/Wallets/SyncHDLeaf.cpp

http://185.213.153.35:8081/browse/BST-2747

Require 1 conf for external addresses too

---

BlocksettleNetworkingLib/BsClient.cpp
BlocksettleNetworkingLib/BsClient.h
BlocksettleNetworkingLib/DataConnectionListener.h
BlocksettleNetworkingLib/RouterServerConnection.cpp
BlocksettleNetworkingLib/RouterServerConnection.h
BlocksettleNetworkingLib/ServerConnection.h
BlocksettleNetworkingLib/ServerConnectionListener.h
BlocksettleNetworkingLib/WsConnection.cpp
BlocksettleNetworkingLib/WsConnection.h
BlocksettleNetworkingLib/WsDataConnection.cpp
BlocksettleNetworkingLib/WsDataConnection.h
BlocksettleNetworkingLib/WsServerConnection.cpp
BlocksettleNetworkingLib/WsServerConnection.h
BlocksettleNetworkingLib/ZMQ_BIP15X_ServerConnection.cpp
BlocksettleNetworkingLib/ZMQ_BIP15X_ServerConnection.h
BlocksettleNetworkingLib/ZmqServerConnection.cpp
BlocksettleNetworkingLib/ZmqServerConnection.h
BlocksettleNetworkingLib/ZmqStreamServerConnection.cpp
BlocksettleNetworkingLib/ZmqStreamServerConnection.h
WalletsLib/CoreWallet.cpp
build_scripts/openssl_settings.py
build_scripts/qt_settings.py
build_scripts/websockets_settings.py

BIP15X will be added later, TLS will be used for now.

Add WebSocket connection

---

CommonLib/ScopeGuard.h

Issue: add function to make possible release cb from scropedGuard before object destruction

Add possibility to release cb in scoped guard

---

BlocksettleNetworkingLib/ApplicationSettings.cpp
BlocksettleNetworkingLib/ApplicationSettings.h

Issue: add info widget flag for showing info dialog for new comer user

Add flag for showing welcome banner

---

BlocksettleNetworkingLib/ApplicationSettings.cpp
BlocksettleNetworkingLib/ApplicationSettings.h

Issue: http://185.213.153.35:8081/browse/BST-2760
add flags for auto quoting and auto signing

Add flags for auto quoting and signing to settings

---

BlocksettleNetworkingLib/TransportBIP15x.cpp
BlocksettleNetworkingLib/TransportBIP15x.h

Prevent infinite recursion when re-keying by data size.

BIP15x rekey fix

---

BlocksettleNetworkingLib/CommonTypes.cpp
BlocksettleNetworkingLib/CommonTypes.h

Add MdInfo class

---

BlocksettleNetworkingLib/AddressVerificator.cpp
BlocksettleNetworkingLib/AuthAddressLogic.cpp
BlocksettleNetworkingLib/AuthAddressLogic.h
Blocksettle_proto/Communication/bs_server.proto
WalletsLib/Address.cpp
WalletsLib/Address.h

Mostly added new async methods to allow message processing while waiting for Armory messages in the message queue loop.

Auth logic improvements and fixes

---

BlocksettleNetworkingLib/AuthAddressLogic.cpp
BlocksettleNetworkingLib/AuthAddressLogic.h
WalletsLib/ArmoryConnection.cpp

fix AuthAddressLogic shutdown sequence

AuthAddressLogic: AWA shutdown and recovery

---

Blocksettle_proto/Communication/bs_server_storage.proto

Please merge with corresponding PR for PB

Update messages for storage adapter

---

BlocksettleNetworkingLib/AuthAddressManager.cpp
BlocksettleNetworkingLib/AuthAddressManager.h
BlocksettleNetworkingLib/BSErrorCode.h
BlocksettleNetworkingLib/BsClient.cpp
BlocksettleNetworkingLib/BsClient.h
Blocksettle_proto/Communication/bs_proxy_pb.proto
Blocksettle_proto/Communication/bs_proxy_terminal.proto
Blocksettle_proto/Communication/bs_server.proto

Use status code for auth address submit

---

Blocksettle_proto/Communication/bs_server.proto

Remove dead messages

---

BlocksettleNetworkingLib/AuthAddressLogic.cpp
BlocksettleNetworkingLib/AuthAddressLogic.h

Pretty print methods for validation address structs. Mostly a debug feature.

AuthAddress state pretty print

---

WalletsLib/CoreWallet.cpp

This change should fix CC amounts display on requester side.

Filtering for input amount

---

BlocksettleNetworkingLib/Wallets/SyncWalletsManager.cpp

Fix problem with low CC network fee.

Fix CC fee

---

BlocksettleNetworkingLib/Bip21Types.h
BlocksettleNetworkingLib/BitPayRequests.cpp
BlocksettleNetworkingLib/BitPayRequests.h
BlocksettleNetworkingLib/JsonTools.cpp
BlocksettleNetworkingLib/JsonTools.h
BlocksettleNetworkingLib/SignContainer.cpp
BlocksettleNetworkingLib/SignContainer.h

To support Bip21 and BitPay requests.

Bip21 bitpay support

---

build_scripts/CMakeModules/LinkerFlags.cmake

Add module to force non-executable stack

Add noexecstack gcc/clang cmake module

---

BlocksettleNetworkingLib/QSeed.cpp
BlocksettleNetworkingLib/QSeed.h
WalletsLib/CoreHDGroup.cpp
cppForSwig/CMakeLists.txt

This is to allow wallet import in new terminal arch branch, as new and old export routines produce different output.

use Armory easy16 backup code

---

BlocksettleNetworkingLib/Adapters/BlockchainAdapter.cpp
BlocksettleNetworkingLib/Message/Bus.cpp
BlocksettleNetworkingLib/Message/Envelope.h
Blocksettle_proto/Communication/bs_server.proto

- definitions required for PB request 
- replace system_clock in adapter bus with steady_clock to protect timers from system clock changes.

Price book updates

---

BlocksettleNetworkingLib/SslDataConnection.cpp
build_scripts/openssl_settings.py
build_scripts/websockets_settings.py

- update openSsl lib to latest release version
- update libWS to latest release version
- use system certificates on Windows ( linux/OSX still failing to verify server certiicate if no certificate bundle provided )

Load system certificates

---

build_scripts/amqpcpp_settings.py
build_scripts/libuv_settings.py

Update LibUV and Amqp-cpp libs to latest releases

Update libuv ampqcpp

---

BlocksettleNetworkingLib/Adapters/WalletsAdapter.cpp
BlocksettleNetworkingLib/AssetManager.cpp
BlocksettleNetworkingLib/AuthAddressLogic.cpp
BlocksettleNetworkingLib/TradesUtils.cpp
BlocksettleNetworkingLib/TransactionData.cpp
BlocksettleNetworkingLib/Wallets/SyncWallet.cpp
BlocksettleNetworkingLib/Wallets/SyncWalletsManager.cpp
WalletsLib/BTCNumericTypes.h
WalletsLib/XBTAmount.h

Update to a XBT Amount class to use signed int

Price volume types

---

BlocksettleNetworkingLib/Message/Adapter.cpp
BlocksettleNetworkingLib/Message/ThreadedAdapter.cpp
BlocksettleNetworkingLib/Message/ThreadedAdapter.h
Blocksettle_proto/Communication/bs_fut_storage.proto
Blocksettle_proto/Communication/bs_server.proto
Blocksettle_proto/Communication/pb_cli.proto
build_scripts/qt_settings.py

- fix threaded adapter to properly process deferred envelopes in internal q
- remove deprecated genoa status reporting stuff
- minor fix for qt build script on windows for server ( no need to update script revision )

Test session flow

---

Blocksettle_proto/Communication/bs_server.proto

FX & XBT amount/value types in futures related protobuf definitions

Amount value update

---

Blocksettle_proto/Communication/bs_api_server.proto
Blocksettle_proto/Communication/bs_fut_storage.proto
Blocksettle_proto/Communication/bs_server.proto

This is a cherry pick required to support changes in fee history merged to ses_manager_roll branch in FBE repo.

product rename

---

CommonLib/ManualResetEvent.cpp
CommonLib/ManualResetEvent.h
CommonLib/ProcessingThread.h

Mainly for Dealer usage, not used widely in the other code.

Processing thread fixes

---

Blocksettle_proto/Communication/bs_server.proto

minor renaming around payout dry run proto forma

Minor resolve session updates
